### ISSUE TITLE
CUFFT_INTERNAL_ERROR on TTS and RVC inference

### ISSUE THREAD

**Issue by DanHues** [IAHispano/Applio-RVC-Fork#136]
### Environment
- **OS:** Ubuntu 22.04.3 LTS
- **Python Version:** 3.11.5
- **Conda Environment:** Yes
- **CUDA Version 12.2**
- **Hardware:** 4060 8gb VRAM Laptop

### Issue Description
Whether it be through the TTS or the model inference I am encountering this error consistently ```RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR```

###Attempted sollutions
- I have updated CUDA drivers and backdated them from versions **11.5 to 12.2**
- Downgraded and updated pytorch from versions 2.0.0, 2.0.0cu118, 2.0.0cu117, 2.1.1, 2.2.2 and the nightly binaries
- reinstalled Applio

```2023-11-21 15:51:05 | WARNING | lib.infer.modules.vc.modules | Traceback (most recent call last):
  File "/home/d/Desktop/aihub/Applio-RVC-Fork/lib/infer/modules/vc/modules.py", line 534, in vc_single_dont_save
	audio_opt = self.pipeline.pipeline(
  File "/home/d/Desktop/aihub/Applio-RVC-Fork/lib/infer/modules/vc/pipeline.py", line 686, in pipeline
	pitch, pitchf = self.get_f0(
  File "/home/d/Desktop/aihub/Applio-RVC-Fork/lib/infer/modules/vc/pipeline.py", line 424, in get_f0
	f0 = self.model_rmvpe.infer_from_audio(x, thred=0.03)
  File "/home/d/Desktop/aihub/Applio-RVC-Fork/lib/infer/infer_libs/rmvpe.py", line 616, in infer_from_audio
	mel = self.mel_extractor(
  File "/home/d/Desktop/aihub/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
	return forward_call(*args, **kwargs)
  File "/home/d/Desktop/aihub/Applio-RVC-Fork/lib/infer/infer_libs/rmvpe.py", line 530, in forward
	fft = torch.stft(
  File "/home/d/Desktop/aihub/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/torch/functional.py", line 641, in stft
	return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR

'NoneType' object has no attribute 'dtype'
```

**Comment by Aldair502** [comment]
applio doesn't work with 3.10 on windows tho

**Comment by Aldair502** [comment]
> * **Python Version:** 3.11.5

Are you sure?

>   File "/home/d/Desktop/aihub/Applio-RVC-Fork/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl

This doesn't even use conda. applio runs in a venv

> * **Conda Environment:** Yes

About this applio have weird behaviors on linux due is clossplatform and the python versions differ. win use 3.9 and unix like systems 3.11 so i hope you can understand the issue.

Check in the discord for better support
